In [1]:
import pandas as pd
import numpy as np

df_all = pd.read_csv("cortical_metrics_1.4.csv")

# Exc and PV have sufficient number of cells, so we'll filter out non-V1 Exc and PV.
# SST and VIP are small populations, so let's keep also non-V1 neurons
exclude = (
    df_all["cell_type"].isnull()
    | df_all["cell_type"].str.contains("EXC")
    | df_all["cell_type"].str.contains("PV")
) & (df_all["ecephys_structure_acronym"] != "VISp")

df = df_all[~exclude]
print(f"Original: {df_all.shape[0]} cells,   filtered: {df.shape[0]} cells")

/tmp/ipykernel_1043920/3923305366.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

/tmp/ipykernel_1043920/3923305366.py:4: DtypeWarning: Columns (60,62,65,67,69,72,119,123) have mixed types. Specify dtype option on import or set low_memory=False.
  df_all = pd.read_csv("cortical_metrics_1.4.csv")

Original: 40294 cells,   filtered: 8799 cells

In [13]:
# Count the number of observation from every session type
bo_counts = df[df["session_type"] == "brain_observatory_1.1"]["cell_type"].value_counts()
fc_counts = df[df["session_type"] == "functional_connectivity"]["cell_type"].value_counts()

# Some cells have very large values of RF. They are likely not-good fits, so ignore.
df.loc[(df["width_rf"] > 100), "width_rf"] = np.nan
df.loc[(df["height_rf"] > 100), "height_rf"] = np.nan

# define contrast response types
types = ["high", "band", "low"]
type_fracs = {}
type_fracs_err = {}
contrast_responsive = df["sig0.01"] == True
contrast_responsive_counts = df[contrast_responsive]["cell_type"].value_counts()
for t in types:
    type_counts = df[(df["best_model"] == t) & contrast_responsive]["cell_type"].value_counts()
    n = contrast_responsive_counts
    p = type_counts / n
    type_fracs[t] = p
    type_fracs_err[t] = np.sqrt(p * (1 - p) / n)

# Save the processed table
df.to_csv("LM_OSI_DSI_DF.csv", sep=" ", index=False)

In [14]:
# set group statistics, and insert the cell counts for convenience
resource_tables = {}
resource_tables["median"] = df.groupby("cell_type").median(numeric_only=True)
resource_tables["mean"] = df.groupby("cell_type").mean(numeric_only=True)
resource_tables["sem"] = df.groupby("cell_type").sem(numeric_only=True)

for t in resource_tables.values():
    # insert counts and fractional elements that is common for all 3 tables
    t.insert(0, "n_cells_BO", bo_counts)
    t.insert(1, "n_cells_FC", fc_counts)
    t["n_cells_FC"][t["n_cells_FC"].isna()] = 0
    t["n_cells_FC"] = t["n_cells_FC"].astype(dtype=int)

    # t.insert(-1, "frac_highpass", type_fracs["high"])
    t["frac_highpass"] = type_fracs["high"]
    t["frac_bandpass"] = type_fracs["band"]
    t["frac_lowpass"] = type_fracs["low"]

# sem is a special case. re-insert the estimated error of the fraction
resource_tables["sem"]["frac_highpass"] = type_fracs_err["high"]
resource_tables["sem"]["frac_bandpass"] = type_fracs_err["band"]
resource_tables["sem"]["frac_lowpass"] = type_fracs_err["low"]

<ipython-input-14-a303acd7ca0a>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t["n_cells_FC"][t["n_cells_FC"].isna()] = 0
<ipython-input-14-a303acd7ca0a>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t["n_cells_FC"][t["n_cells_FC"].isna()] = 0
<ipython-input-14-a303acd7ca0a>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t["n_cells_FC"][t["n_cells_FC"].isna()] = 0

In [6]:
selected_metrics = [
    "n_cells_BO",
    "n_cells_FC",
    "g_osi_dg",
    "g_dsi_dg",
    "pref_sf_sg",
    "pref_tf_dg",
    "firing_rate_sp",
    "firing_rate_rf",
    "firing_rate_dg",
    "width_rf",
    "height_rf",
    "fano_dg",
    "frac_highpass",
    "frac_bandpass",
    "frac_lowpass",
]

# For the full list of metrics, refer to list(df.columns)
#
# See https://allensdk.readthedocs.io/en/latest/visual_coding_neuropixels.html
# for detailed descriptions of the metrics.

In [15]:
pd.set_option("display.float_format", "{:0.2f}".format)
print('Median functional responses')
resource_tables["median"][selected_metrics]

Median functional responses

,n_cells_BO,n_cells_FC,g_osi_dg,g_dsi_dg,pref_sf_sg,pref_tf_dg,firing_rate_sp,firing_rate_rf,firing_rate_dg,width_rf,height_rf,fano_dg,frac_highpass,frac_bandpass,frac_lowpass
cell_type,,,,,,,,,,,,,,,
ALL_L1,50,91,0.18,0.11,0.04,2.00,2.21,0.00,0.40,25.90,28.65,3.37,0.83,0.17,NaN
EXC_L23,49,67,0.27,0.14,0.04,2.00,0.81,0.62,0.84,16.38,18.69,3.16,0.64,0.25,0.11
EXC_L4,89,190,0.17,0.11,0.04,2.00,1.85,1.37,2.09,20.28,19.59,3.76,0.53,0.31,0.16
EXC_L5,328,449,0.20,0.09,0.08,2.00,2.95,2.57,3.21,32.81,37.10,3.79,0.71,0.21,0.08
EXC_L6,106,155,0.18,0.08,0.08,2.00,2.18,1.38,2.76,41.92,48.06,4.15,0.77,0.16,0.07
PV_L23,13,30,0.12,0.09,0.04,2.00,5.41,3.34,6.55,15.56,21.73,7.01,0.80,0.16,0.04
PV_L4,12,40,0.14,0.11,0.02,2.00,6.49,4.35,8.08,17.81,20.61,5.99,0.70,0.20,0.10
PV_L5,45,63,0.12,0.06,0.08,2.00,8.17,6.20,12.06,31.09,37.76,6.41,0.79,0.21,NaN
PV_L6,16,23,0.10,0.04,0.04,2.00,11.70,11.37,18.46,49.65,61.43,5.19,0.93,0.07,NaN
SST_L23,3,15,0.10,0.10,0.04,2.00,3.82,3.93,8.38,30.68,29.03,6.49,0.67,0.33,NaN
SST_L4,2,7,0.10,0.04,0.16,2.00,3.82,3.88,8.55,31.53,41.58,3.56,0.50,0.50,NaN
SST_L5,2,25,0.11,0.03,0.04,2.00,3.92,4.86,8.35,42.42,51.94,3.74,0.81,0.19,NaN
SST_L6,1,15,0.14,0.11,0.02,2.00,10.28,6.72,13.88,51.94,49.98,7.16,0.78,0.11,0.11
VIP_L23,5,0,0.16,0.15,0.02,1.00,14.74,10.74,8.70,41.29,84.06,15.26,NaN,NaN,NaN
VIP_L4,1,2,0.06,0.01,0.32,2.00,3.14,0.98,2.35,37.44,17.73,8.66,NaN,NaN,NaN
VIP_L5,2,3,0.05,0.07,0.05,2.00,11.57,6.05,12.22,92.97,55.62,5.17,1.00,NaN,NaN
VIP_L6,1,2,0.12,0.10,0.04,2.00,6.73,1.37,7.94,41.84,38.97,3.41,1.00,NaN,NaN

In [9]:
print('Mean functional responses')
resource_tables["mean"][selected_metrics]

Mean functional responses

,n_cells_BO,n_cells_FC,g_osi_dg,g_dsi_dg,pref_sf_sg,pref_tf_dg,firing_rate_sp,firing_rate_rf,firing_rate_dg,width_rf,height_rf,fano_dg,frac_highpass,frac_bandpass,frac_lowpass
cell_type,,,,,,,,,,,,,,,
ALL_L1,50,91,0.33,0.26,0.06,2.34,4.61,0.77,1.34,2.35,16.26,4.28,0.83,0.17,NaN
EXC_L23,203,300,0.36,0.25,0.10,2.48,1.53,1.28,1.39,13.30,20.43,3.90,0.54,0.29,0.18
EXC_L4,301,328,0.26,0.17,0.11,2.83,3.57,2.75,3.52,26.94,30.80,55.90,0.61,0.30,0.09
EXC_L5,482,493,0.27,0.12,0.10,3.56,5.71,4.40,5.68,34.17,38.27,4.60,0.71,0.23,0.06
EXC_L6,191,153,0.45,0.13,0.10,3.39,3.09,2.62,3.52,34.15,33.82,5.05,0.76,0.18,0.06
PV_L23,75,58,0.13,0.11,0.10,2.02,7.93,5.40,6.57,21.90,25.46,8.25,0.67,0.17,0.17
PV_L4,98,81,0.13,0.09,0.08,2.47,10.47,7.07,9.27,29.37,32.41,8.76,0.62,0.22,0.16
PV_L5,99,101,0.14,0.07,0.10,3.13,11.96,9.38,14.02,33.41,38.48,10.53,0.79,0.15,0.06
PV_L6,56,34,0.18,0.07,0.10,3.31,12.29,9.20,14.36,46.73,46.02,7.62,0.81,0.15,0.04
SST_L23,3,15,0.08,0.11,0.03,2.78,5.27,5.48,9.87,36.45,34.41,8.27,0.67,0.33,NaN
SST_L4,2,7,0.10,0.04,0.16,2.11,3.85,5.29,8.91,36.06,37.63,4.74,0.50,0.50,NaN
SST_L5,2,25,0.11,0.03,0.04,2.44,7.59,6.47,10.08,50.78,55.62,5.63,0.81,0.19,NaN
SST_L6,1,15,0.14,0.11,0.02,1.94,12.25,9.26,14.56,51.92,57.63,8.17,0.78,0.11,0.11
VIP_L23,5,0,0.14,0.13,0.05,2.60,12.64,10.18,9.39,40.63,73.76,14.20,NaN,NaN,NaN
VIP_L4,1,2,0.06,0.01,0.32,6.33,3.38,0.90,2.36,37.44,17.73,8.78,NaN,NaN,NaN
VIP_L5,2,3,0.05,0.07,0.05,4.40,14.14,12.36,17.17,92.97,55.51,4.97,1.00,NaN,NaN
VIP_L6,1,2,0.12,0.10,0.04,6.33,6.36,2.76,6.62,41.84,38.97,3.97,1.00,NaN,NaN

In [10]:
print("SEM of functional responses")
resource_tables["sem"][selected_metrics]

SEM of functional responses

,n_cells_BO,n_cells_FC,g_osi_dg,g_dsi_dg,pref_sf_sg,pref_tf_dg,firing_rate_sp,firing_rate_rf,firing_rate_dg,width_rf,height_rf,fano_dg,frac_highpass,frac_bandpass,frac_lowpass
cell_type,,,,,,,,,,,,,,,
ALL_L1,50,91,0.04,0.04,0.01,0.20,1.11,0.17,0.19,26.06,14.63,0.39,0.15,0.15,NaN
EXC_L23,203,300,0.02,0.01,0.01,0.12,0.13,0.26,0.10,4.98,1.38,0.24,0.04,0.04,0.03
EXC_L4,301,328,0.01,0.01,0.01,0.13,0.16,0.17,0.17,1.96,1.09,51.61,0.04,0.03,0.02
EXC_L5,482,493,0.01,0.01,0.00,0.13,0.16,0.18,0.15,0.97,1.20,0.19,0.03,0.02,0.01
EXC_L6,191,153,0.02,0.01,0.01,0.22,0.18,0.19,0.16,2.23,3.27,0.28,0.05,0.04,0.03
PV_L23,75,58,0.01,0.01,0.01,0.20,0.49,0.50,0.43,1.31,1.67,0.58,0.08,0.06,0.06
PV_L4,98,81,0.01,0.01,0.01,0.19,0.63,1.02,0.48,1.53,1.66,0.66,0.07,0.06,0.05
PV_L5,99,101,0.01,0.01,0.01,0.27,0.78,0.90,0.84,1.76,2.00,0.88,0.05,0.04,0.03
PV_L6,56,34,0.02,0.01,0.01,0.44,1.10,1.24,1.26,3.40,4.16,0.67,0.08,0.07,0.04
SST_L23,3,15,0.02,0.02,0.01,0.73,1.19,1.12,1.63,5.93,6.47,1.15,0.14,0.14,NaN
SST_L4,2,7,0.04,0.01,0.00,0.26,1.15,1.09,1.49,9.70,8.99,1.13,0.20,0.20,NaN
SST_L5,2,25,0.02,0.00,0.00,0.48,1.57,1.18,1.39,5.85,6.71,1.29,0.10,0.10,NaN
SST_L6,1,15,NaN,NaN,NaN,0.06,2.20,2.00,2.56,11.00,14.98,1.39,0.14,0.10,0.10
VIP_L23,5,0,0.05,0.03,0.03,1.36,3.57,2.41,3.45,3.78,12.22,2.88,NaN,NaN,NaN
VIP_L4,1,2,NaN,NaN,NaN,4.33,0.99,0.31,0.78,19.91,NaN,3.65,NaN,NaN,NaN
VIP_L5,2,3,0.03,0.04,0.03,2.66,5.45,6.97,7.32,NaN,4.31,1.56,0.00,NaN,NaN
VIP_L6,1,2,NaN,NaN,NaN,4.33,2.07,1.62,1.85,15.01,NaN,1.81,0.00,NaN,NaN